services:

  bot:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "80:80/udp"
      - "12345:12345"
      - "2345:2345"
    volumes:
      - .:/app
    command: bash -c "go mod tidy && air /cmd/main.go -b 0.0.0.0"

  # tailwind compiler for dev
  tailwind:
    image: node:lts-slim
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: bash -c "npm i tailwindcss && npx tailwindcss -i ./static/css/config.css -o ./static/css/min.style.css --minify --watch"
