services:
  bot:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "80:80/udp"
      - "12345:12345"
    volumes:
      - .:/app
    command: bash -c "go mod tidy && air /cmd/main.go -b 0.0.0.0"
