name: Bot CD

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  compile-binary-and-release:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.artifact-upload.outputs.artifact-id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Install dependencies
        run: go mod tidy
      - name: Build app
        run: GOOS=linux GOARCH=amd64 go build -v -o ./meeting-mate ./cmd/meeting-mate
      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: app-artifact
          path: './meeting-mate'
          if-no-files-found: error
          retention-days: 1
      - name: Create new release
        uses: softprops/action-gh-release@v2
        with:
          files: ./meeting-mate
          fail_on_unmatched_files: true
          make_latest: true
          generate_release_notes: true

  notify-prod-server:
    needs: compile-binary-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Invoke webhook
        uses: johannes-huther/webhook.sh@v1
        env:
          webhook_url: ${{ secrets.BOT_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"artifact-id": "${{ needs.compile-binary.outputs.artifact-id }}"}'
