name: Site CD

on:
  push:
    branches: ["main"]
    paths:
      - "static/**"

# Cancel the workflow in progress if newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  zip-static:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.artifact-upload.outputs.artifact-id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            static/css/min.style.css
            static/images
            static/js
            static/index.html
          sparse-checkout-cone-mode: false
      - name: Upload static dir as artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: app-artifact
          path: "static"
          if-no-files-found: error
          retention-days: 1

  notify-prod-server:
    needs: zip-static
    runs-on: ubuntu-latest
    steps:
      - name: Invoke webhook
        uses: johannes-huther/webhook.sh@v1
        env:
          webhook_url: ${{ secrets.STATIC_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"artifact-id": "${{ needs.zip-static.outputs.artifact-id }}"}'
